### ISSUE TITLE
Progressive enhancement

### ISSUE THREAD

**Issue by datashaman** [VizuaaLOG/microlib-tabs#13]
The styles that the page is loaded with leave the tabs invisible until the Javascript makes them visible. For primitive browsers which don't support Javascript, default visible would be better. Then the page still functions if the Javascript does not load, it just does not function optimally.

As it is now, you cannot see the tabs on the page when you disable Javascript.

**Comment by VizuaaLOG** [comment]
The styles provided are for example purposes. The point of this lib is to provide the JS integration without an opinionated style for the UI.

If in your project you would like the tabs always visible then you do this within your CSS. No changes to the library will be required.
